#version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: locker-app
    ports:
      - "8080:8080"
    environment:
      # Spring Datasource config (point to the "db" service)
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # Twilio credentials (replace with your actual account SID/auth token)
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}

    depends_on:
      - db
  
  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    command:
      - "http"
      - "locker-app:8080"
      - "--url=hawk-capable-greatly.ngrok-free.app"
    ports:
    # Optional: add if you need the dashboard
      - "4040:4040"

  db:
    image: mysql:8
    container_name: locker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
